/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/app.config`; params?: Router.UnknownInputParams; } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/collect` | `/collect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownInputParams; } | { pathname: `/api/apiArea`; params?: Router.UnknownInputParams; } | { pathname: `/api/apiframe`; params?: Router.UnknownInputParams; } | { pathname: `/api/apiUser`; params?: Router.UnknownInputParams; } | { pathname: `/api/axiosClient`; params?: Router.UnknownInputParams; } | { pathname: `/modelload/yolo`; params?: Router.UnknownInputParams; } | { pathname: `/modelload/yoloDecode`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/loginscreen`; params?: Router.UnknownInputParams; } | { pathname: `/types/react-native-fast-tflite.d`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/app.config`; params?: Router.UnknownOutputParams; } | { pathname: `/config`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/collect` | `/collect`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownOutputParams; } | { pathname: `/api/apiArea`; params?: Router.UnknownOutputParams; } | { pathname: `/api/apiframe`; params?: Router.UnknownOutputParams; } | { pathname: `/api/apiUser`; params?: Router.UnknownOutputParams; } | { pathname: `/api/axiosClient`; params?: Router.UnknownOutputParams; } | { pathname: `/modelload/yolo`; params?: Router.UnknownOutputParams; } | { pathname: `/modelload/yoloDecode`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/loginscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/types/react-native-fast-tflite.d`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/app.config${`?${string}` | `#${string}` | ''}` | `/config${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/collect${`?${string}` | `#${string}` | ''}` | `/collect${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/me${`?${string}` | `#${string}` | ''}` | `/me${`?${string}` | `#${string}` | ''}` | `/api/apiArea${`?${string}` | `#${string}` | ''}` | `/api/apiframe${`?${string}` | `#${string}` | ''}` | `/api/apiUser${`?${string}` | `#${string}` | ''}` | `/api/axiosClient${`?${string}` | `#${string}` | ''}` | `/modelload/yolo${`?${string}` | `#${string}` | ''}` | `/modelload/yoloDecode${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/screens/auth/loginscreen${`?${string}` | `#${string}` | ''}` | `/types/react-native-fast-tflite.d${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/app.config`; params?: Router.UnknownInputParams; } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/collect` | `/collect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownInputParams; } | { pathname: `/api/apiArea`; params?: Router.UnknownInputParams; } | { pathname: `/api/apiframe`; params?: Router.UnknownInputParams; } | { pathname: `/api/apiUser`; params?: Router.UnknownInputParams; } | { pathname: `/api/axiosClient`; params?: Router.UnknownInputParams; } | { pathname: `/modelload/yolo`; params?: Router.UnknownInputParams; } | { pathname: `/modelload/yoloDecode`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/loginscreen`; params?: Router.UnknownInputParams; } | { pathname: `/types/react-native-fast-tflite.d`; params?: Router.UnknownInputParams; };
    }
  }
}
